name: stves1/ci-test
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  packageA:
    name: packageA-.gitlab-ci
    uses: stves/actions-importer-templates/.github/workflows/packagea-.gitlab-ci.yml@v2
  packageB:
    name: packageB-.gitlab-ci
    uses: "./.github/workflows/reusable-workflows-packageb-.gitlab-ci.yml"
  packageC:
    name: packageC-.gitlab-ci
    uses: stves/actions-importer-templates/.github/workflows/packagec-.gitlab-ci.yml@main
