name: Get Last Run Status
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    environment: CI
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v6
      id: last-workflow-status
      with:
        script: |
          currentWorkflowId = (
            await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            })
          ).data.workflow_id
          
          runsList = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: currentWorkflowId,
            status: 'completed',
            branch: '${{ env.BRANCH_NAME }}',
            per_page: 1
          });

          return runsList.data.workflow_runs[0].conclusion
    - name: Get result
      run: echo "${{steps.last-workflow-status.outputs.result}}"
