name: Slack (freestyle project)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    environment: CI
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: run command
      shell: bash
      run: |-
        echo "henlo"
        mkdir -p artifacts
        echo 'This is an artifact' >> artifacts/one.txt
    - name: run command
      shell: bash
      run: |-
        mkdir -p artifacts
        echo 'This is from another build step' >> artifacts/two.txt
        exit 0
    - name: slack-notify-on-action-start
      uses: rtCamp/action-slack-notify@v2.2.0
      if: success()
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
        SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
        SLACK_USERNAME: hey-its-jenkins
        SLACK_ICON_EMOJI: :shipit:
    - id: last_build_status
      uses: MercymeIlya/last-workflow-status@v0.3.3
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: rtCamp/action-slack-notify@v2.2.0
      if: success()
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
        SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
        SLACK_USERNAME: hey-its-jenkins
        SLACK_ICON_EMOJI: :shipit:
        SLACK_COLOR: success
    - uses: rtCamp/action-slack-notify@v2.2.0
      if: failure() && steps.last_build_status.outputs.last_status == 'success'
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
        SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
        SLACK_USERNAME: hey-its-jenkins
        SLACK_ICON_EMOJI: :shipit:
        SLACK_COLOR: failure
    - uses: rtCamp/action-slack-notify@v2.2.0
      if: cancelled()
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
        SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
        SLACK_USERNAME: hey-its-jenkins
        SLACK_ICON_EMOJI: :shipit:
        SLACK_COLOR: cancelled
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: artifacts/
